### ISSUE TITLE
Fiks reset should also clear stash?

### ISSUE THREAD

**Issue by eldoy** [eldoy/fiks#12]
Is it problematic to clear the stash `git stash clear` for all directories if we want to reset?

**Comment by acmb** [comment]
It should be quick and easy to implement this feature. I only fear the possibility of unintentionally losing stashed changes that were not automatically created by `fiks`.

Maybe some developers may use and keep stashed changes for longer than others as part of their development processes? Maybe `fiks` stashes can also come in handy if we encounter some unexpected error along the way?

Besides this, I don't see any problem in clearing stash on reset, if that's the behaviour we want.

**Comment by eldoy** [comment]
How about just doing a "All changes including the stash will be lost. Hit enter to continue."

And then Ctrl + C will cancel.

**Comment by acmb** [comment]
Looks good! Working on it 👍
