### ISSUE TITLE
Fiks install: Update packages

### ISSUE THREAD

**Issue by acmb** [eldoy/fiks#16]
We may want to update packages on `fiks install`, as in some scenarios we were using the wrong package version.

At the same time, maybe our repo was only missing a push with `fiks update` and the extra update step on `fiks install` may not be needed.

**Comment by eldoy** [comment]
@acmb So maybe we can do update on packages from git, and install for the rest?

**Comment by eldoy** [comment]
@acmb Most of the time, I just do `fiks pull` and I expect everything to be working with correct versions. When I do `fiks install` I only want to update all the packages. If I do `fiks update` then I expect to upgrade all packages to the latest versions.

Packages from git are not versioned, and should always be updated to the latest version. So:

* `fiks pull` should also do `fiks install`
* `fiks install` does npm install for normal packages and npm update for git packages
* `fiks update` does npm-check-updates for normal packages, and npm update for git packages

Does this sound reasonable?
