### ISSUE TITLE
Fiks update?

### ISSUE THREAD

**Issue by eldoy** [eldoy/fiks#5]
Do we need update? Or is upgrade enough?

Is it really necessary to ever do `npm update` vs `npm-check-updates`?

If not, maybe `update` should be `npm-check-updates && npm install` and remove `upgrade`?

**Comment by acmb** [comment]
Maybe it is a bit redundant to have `fiks update` and `fiks upgrade`.

According to my tests and research, these are my notes on `npm update` vs `npm-check-updates`:
1. `npm update` updates dependencies and installs the ones that are missing, avoiding an extra **_npm install_** step.
2. `npm-check-updates` simply checks which versions can be updated, requiring an extra **_npm install_** step.
3. Both have an option that updates `package.json`.
4. They seem to use a different logic to determine the new version of a package ([npm update](https://docs.npmjs.com/cli/v10/commands/npm-update#example) vs [npm-check-updates](https://www.npmjs.com/package/npm-check-updates#how-dependency-updates-are-determined)):
    - For instance, running both commands on `firmalisten-api` results in different new versions:
        - `npm update`: waveorb ^0.42.4 >> ^0.**42.7**
        - `npm-check-updates`: waveorb ^0.42.4 >> ^0.**43.0** 

What would your thoughts be on the above? I'm also failing to think of a scenario where we would want to update packages and install missing ones without upgrading (this is, updating package.json).

**Comment by eldoy** [comment]
I never use `npm update` normally, only npm-check-updates, so just go for that I guess.
