### ISSUE TITLE
Git log to JSON

### ISSUE THREAD

**Issue by eldoy** [eldoy/fiks#7]
https://gist.github.com/varemenos/e95c2e098e657c7688fd

Maybe this helps?

**Comment by acmb** [comment]
Hei, @eldoy!

The gist above does seem helpful. 

But do we want `fiks log` to print git logs in JSON format? Or would this be a `fiks log` option?
Do we want to keep printing the same fields we currently do (date, commit, repo, user, message)?

**Comment by eldoy** [comment]
No, just internally maybe it's easier to work with a JSON structure? I thought maybe we needed to convert the git log into an array of data or something.

**Comment by acmb** [comment]
We're already transforming git logs into a JSON array. I tried replacing our parsing logic with this gist and it worked great at first. But unfortunately it started breaking when I used it in a repo that contained a commit with a subject that used quotes.

Given that our custom parser currently seems to work, I didn't push these changes.
Still, I saved them locally in a separate branch.
Please let me know if you'd like to invest some more time into this.

**Comment by eldoy** [comment]
Ok, no, if it works, then it's good.
